[rich]
panel_style = "on #212121"
table_header_style = "bold #d0d0d0 on #303030"
table_title_style = "bold #d0d0d0"
table_border_style = "#6c99bb"
panel_border_style = "#6c99bb"
column_output = "bold #d0d0d0"
column_value = "#d0d0d0"
bright_black = "#505050"
bright_blue = "#6c99bb"
bright_cyan = "#7dd6cf"
bright_green = "#7e8e50"
bright_magenta = "#9f4e85"
bright_red = "#ac4142"
bright_white = "#f5f5f5"
bright_yellow = "#e5b567"
normal_black = "#151515"
normal_blue = "#6c99bb"
normal_cyan = "#7dd6cf"
normal_green = "#7e8e50"
normal_magenta = "#9f4e85"
normal_red = "#ac4142"
normal_white = "#d0d0d0"
normal_yellow = "#e5b567"
cursor_cursor = "#d0d0d0"
cursor_text = "#151515"
table_show_lines = false
table_box = "ROUNDED"
panel_padding = [ 0, 2,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#505050"
blue = "#6c99bb"
cyan = "#7dd6cf"
green = "#7e8e50"
magenta = "#9f4e85"
red = "#ac4142"
white = "#f5f5f5"
yellow = "#e5b567"

[colors.cursor]
cursor = "#d0d0d0"
text = "#151515"

[colors.normal]
black = "#151515"
blue = "#6c99bb"
cyan = "#7dd6cf"
green = "#7e8e50"
magenta = "#9f4e85"
red = "#ac4142"
white = "#d0d0d0"
yellow = "#e5b567"

[colors.primary]
background = "#212121"
foreground = "#d0d0d0"

[colors.selection]
background = "#303030"
text = "#d0d0d0"
