[rich]
panel_style = "on #201f1e"
table_header_style = "bold #f3fffd on #25524a"
table_title_style = "bold #eee4d9"
table_border_style = "#b3e8f3"
panel_border_style = "#b3e8f3"
column_output = "bold #eee4d9"
column_value = "#eee4d9"
bright_black = "#777777"
bright_blue = "#b3e8f3"
bright_cyan = "#bcffc7"
bright_green = "#e3f6aa"
bright_magenta = "#cbbaf9"
bright_red = "#ffb9b9"
bright_white = "#efefef"
bright_yellow = "#ffddaa"
normal_black = "#333333"
normal_blue = "#518bfc"
normal_cyan = "#63fad5"
normal_green = "#12c258"
normal_magenta = "#e37bd9"
normal_red = "#da2700"
normal_white = "#bab2b2"
normal_yellow = "#ffc656"
cursor_cursor = "#7a1c1c"
cursor_text = "#fffbf2"
table_show_lines = true
table_box = "DOUBLE_EDGE"
panel_padding = [ 0, 2,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#777777"
blue = "#b3e8f3"
cyan = "#bcffc7"
green = "#e3f6aa"
magenta = "#cbbaf9"
red = "#ffb9b9"
white = "#efefef"
yellow = "#ffddaa"

[colors.cursor]
cursor = "#7a1c1c"
text = "#fffbf2"

[colors.normal]
black = "#333333"
blue = "#518bfc"
cyan = "#63fad5"
green = "#12c258"
magenta = "#e37bd9"
red = "#da2700"
white = "#bab2b2"
yellow = "#ffc656"

[colors.primary]
background = "#201f1e"
foreground = "#eee4d9"

[colors.selection]
background = "#25524a"
text = "#f3fffd"
