[rich]
panel_style = "on #006984"
table_header_style = "bold #eceff1 on #2baeca"
table_title_style = "bold #c5f2ff"
table_border_style = "#9cc4ff"
panel_border_style = "#9cc4ff"
column_output = "bold #c5f2ff"
column_value = "#c5f2ff"
bright_black = "#434758"
bright_blue = "#9cc4ff"
bright_cyan = "#a3f7ff"
bright_green = "#ddffa7"
bright_magenta = "#ddb0f6"
bright_red = "#ff8b92"
bright_white = "#ffffff"
bright_yellow = "#ffe585"
normal_black = "#292d3e"
normal_blue = "#82aaff"
normal_cyan = "#89ebff"
normal_green = "#b4e88d"
normal_magenta = "#e9c1ff"
normal_red = "#ff8288"
normal_white = "#d0d0d0"
normal_yellow = "#f4d69f"
cursor_cursor = "#ffcc00"
cursor_text = "#292d3e"
table_show_lines = true
table_box = "SQUARE"
panel_padding = [ 1, 1,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#ddb0f6"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[colors.cursor]
cursor = "#ffcc00"
text = "#292d3e"

[colors.normal]
black = "#292d3e"
blue = "#82aaff"
cyan = "#89ebff"
green = "#b4e88d"
magenta = "#e9c1ff"
red = "#ff8288"
white = "#d0d0d0"
yellow = "#f4d69f"

[colors.primary]
background = "#006984"
foreground = "#c5f2ff"

[colors.selection]
background = "#2baeca"
text = "#eceff1"
