[rich]
panel_style = "on #282c34"
table_header_style = "bold #272b33 on #b9c0ca"
table_title_style = "bold #b9c0cb"
table_border_style = "#10b1fe"
panel_border_style = "#10b1fe"
column_output = "bold #b9c0cb"
column_value = "#b9c0cb"
bright_black = "#8f9aae"
bright_blue = "#10b1fe"
bright_cyan = "#5fb9bc"
bright_green = "#3fc56b"
bright_magenta = "#ff78f8"
bright_red = "#ff6480"
bright_white = "#ffffff"
bright_yellow = "#f9c859"
normal_black = "#41444d"
normal_blue = "#3476ff"
normal_cyan = "#4483aa"
normal_green = "#25a45c"
normal_magenta = "#7a82da"
normal_red = "#fc2f52"
normal_white = "#cdd4e0"
normal_yellow = "#ff936a"
cursor_cursor = "#ffcc00"
cursor_text = "#282c34"
table_show_lines = true
table_box = "ROUNDED"
panel_padding = [ 1, 2,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#8f9aae"
blue = "#10b1fe"
cyan = "#5fb9bc"
green = "#3fc56b"
magenta = "#ff78f8"
red = "#ff6480"
white = "#ffffff"
yellow = "#f9c859"

[colors.cursor]
cursor = "#ffcc00"
text = "#282c34"

[colors.normal]
black = "#41444d"
blue = "#3476ff"
cyan = "#4483aa"
green = "#25a45c"
magenta = "#7a82da"
red = "#fc2f52"
white = "#cdd4e0"
yellow = "#ff936a"

[colors.primary]
background = "#282c34"
foreground = "#b9c0cb"

[colors.selection]
background = "#b9c0ca"
text = "#272b33"
