[rich]
panel_style = "on #f9f9f9"
table_header_style = "bold #373a41 on #daf0ff"
table_title_style = "bold #373a41"
table_border_style = "#0099e1"
panel_border_style = "#0099e1"
column_output = "bold #373a41"
column_value = "#373a41"
bright_black = "#676a77"
bright_blue = "#0099e1"
bright_cyan = "#6d93bb"
bright_green = "#3cbc66"
bright_magenta = "#ce33c0"
bright_red = "#ff6480"
bright_white = "#d3d3d3"
bright_yellow = "#c5a332"
normal_black = "#373a41"
normal_blue = "#275fe4"
normal_cyan = "#27618d"
normal_green = "#23974a"
normal_magenta = "#823ff1"
normal_red = "#d52753"
normal_white = "#babbc2"
normal_yellow = "#df631c"
cursor_cursor = "#f32759"
cursor_text = "#ffffff"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#676a77"
blue = "#0099e1"
cyan = "#6d93bb"
green = "#3cbc66"
magenta = "#ce33c0"
red = "#ff6480"
white = "#d3d3d3"
yellow = "#c5a332"

[colors.cursor]
cursor = "#f32759"
text = "#ffffff"

[colors.normal]
black = "#373a41"
blue = "#275fe4"
cyan = "#27618d"
green = "#23974a"
magenta = "#823ff1"
red = "#d52753"
white = "#babbc2"
yellow = "#df631c"

[colors.primary]
background = "#f9f9f9"
foreground = "#373a41"

[colors.selection]
background = "#daf0ff"
text = "#373a41"
