[rich]
panel_style = "on #1e1c31"
table_header_style = "bold #1e1c31 on #cbe1e7"
table_title_style = "bold #cbe1e7"
table_border_style = "#91ddff"
panel_border_style = "#91ddff"
column_output = "bold #cbe1e7"
column_value = "#cbe1e7"
bright_black = "#565575"
bright_blue = "#91ddff"
bright_cyan = "#aaffe4"
bright_green = "#95ffa4"
bright_magenta = "#c991e1"
bright_red = "#ff8080"
bright_white = "#cbe3e7"
bright_yellow = "#ffe9aa"
normal_black = "#141228"
normal_blue = "#65b2ff"
normal_cyan = "#63f2f1"
normal_green = "#62d196"
normal_magenta = "#906cff"
normal_red = "#ff5458"
normal_white = "#a6b3cc"
normal_yellow = "#ffb378"
cursor_cursor = "#fbfcfc"
cursor_text = "#ff271d"
table_show_lines = false
table_box = "SIMPLE"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#565575"
blue = "#91ddff"
cyan = "#aaffe4"
green = "#95ffa4"
magenta = "#c991e1"
red = "#ff8080"
white = "#cbe3e7"
yellow = "#ffe9aa"

[colors.cursor]
cursor = "#fbfcfc"
text = "#ff271d"

[colors.normal]
black = "#141228"
blue = "#65b2ff"
cyan = "#63f2f1"
green = "#62d196"
magenta = "#906cff"
red = "#ff5458"
white = "#a6b3cc"
yellow = "#ffb378"

[colors.primary]
background = "#1e1c31"
foreground = "#cbe1e7"

[colors.selection]
background = "#cbe1e7"
text = "#1e1c31"
