[rich]
panel_style = "on #f6f2ee"
table_header_style = "bold #3d2b5a on #e7d2be"
table_title_style = "bold #3d2b5a"
table_border_style = "#4863b6"
panel_border_style = "#4863b6"
column_output = "bold #3d2b5a"
column_value = "#3d2b5a"
bright_black = "#534c45"
bright_blue = "#4863b6"
bright_cyan = "#488d93"
bright_green = "#577f63"
bright_magenta = "#8452d5"
bright_red = "#b3434e"
bright_white = "#f4ece6"
bright_yellow = "#b86e28"
normal_black = "#352c24"
normal_blue = "#2848a9"
normal_cyan = "#287980"
normal_green = "#396847"
normal_magenta = "#6e33ce"
normal_red = "#a5222f"
normal_white = "#f2e9e1"
normal_yellow = "#ac5402"
cursor_cursor = "#3d2b5a"
cursor_text = "#f6f2ee"
table_show_lines = false
table_box = "SQUARE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#534c45"
blue = "#4863b6"
cyan = "#488d93"
green = "#577f63"
magenta = "#8452d5"
red = "#b3434e"
white = "#f4ece6"
yellow = "#b86e28"

[colors.cursor]
cursor = "#3d2b5a"
text = "#f6f2ee"

[colors.normal]
black = "#352c24"
blue = "#2848a9"
cyan = "#287980"
green = "#396847"
magenta = "#6e33ce"
red = "#a5222f"
white = "#f2e9e1"
yellow = "#ac5402"

[colors.primary]
background = "#f6f2ee"
foreground = "#3d2b5a"

[colors.selection]
background = "#e7d2be"
text = "#3d2b5a"
