[rich]
panel_style = "on #141414"
table_header_style = "bold #141414 on #8db8e5"
table_title_style = "bold #bab7b6"
table_border_style = "#688dfd"
panel_border_style = "#688dfd"
column_output = "bold #bab7b6"
column_value = "#bab7b6"
bright_black = "#817e7e"
bright_blue = "#688dfd"
bright_cyan = "#32e0fb"
bright_green = "#37e57b"
bright_magenta = "#ed6fe9"
bright_red = "#ff643b"
bright_white = "#d3d8d9"
bright_yellow = "#fccd1a"
normal_black = "#000000"
normal_blue = "#0575d8"
normal_cyan = "#1db6bb"
normal_green = "#60b442"
normal_magenta = "#af5ed2"
normal_red = "#cf494c"
normal_white = "#bab7b6"
normal_yellow = "#db9c11"
cursor_cursor = "#37e57b"
cursor_text = "#141414"
table_show_lines = false
table_box = "SIMPLE"
panel_padding = [ 1, 2,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#817e7e"
blue = "#688dfd"
cyan = "#32e0fb"
green = "#37e57b"
magenta = "#ed6fe9"
red = "#ff643b"
white = "#d3d8d9"
yellow = "#fccd1a"

[colors.cursor]
cursor = "#37e57b"
text = "#141414"

[colors.normal]
black = "#000000"
blue = "#0575d8"
cyan = "#1db6bb"
green = "#60b442"
magenta = "#af5ed2"
red = "#cf494c"
white = "#bab7b6"
yellow = "#db9c11"

[colors.primary]
background = "#141414"
foreground = "#bab7b6"

[colors.selection]
background = "#8db8e5"
text = "#141414"
