[rich]
panel_style = "on #262c35"
table_header_style = "bold #ffffff on #1a4080"
table_title_style = "bold #ebebeb"
table_border_style = "#17b2e0"
panel_border_style = "#17b2e0"
column_output = "bold #ebebeb"
column_value = "#ebebeb"
bright_black = "#191919"
bright_blue = "#17b2e0"
bright_cyan = "#8bd2ed"
bright_green = "#3d9751"
bright_magenta = "#7830b0"
bright_red = "#bf091d"
bright_white = "#ffffff"
bright_yellow = "#f6bb34"
normal_black = "#191919"
normal_blue = "#17b2e0"
normal_cyan = "#8bd2ed"
normal_green = "#3d9751"
normal_magenta = "#7830b0"
normal_red = "#bf091d"
normal_white = "#ffffff"
normal_yellow = "#f6bb34"
cursor_cursor = "#d9002f"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "DOUBLE_EDGE"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#191919"
blue = "#17b2e0"
cyan = "#8bd2ed"
green = "#3d9751"
magenta = "#7830b0"
red = "#bf091d"
white = "#ffffff"
yellow = "#f6bb34"

[colors.cursor]
cursor = "#d9002f"
text = "#ffffff"

[colors.normal]
black = "#191919"
blue = "#17b2e0"
cyan = "#8bd2ed"
green = "#3d9751"
magenta = "#7830b0"
red = "#bf091d"
white = "#ffffff"
yellow = "#f6bb34"

[colors.primary]
background = "#262c35"
foreground = "#ebebeb"

[colors.selection]
background = "#1a4080"
text = "#ffffff"
