[rich]
panel_style = "on #1f1d27"
table_header_style = "bold #b7a2ff on #353147"
table_title_style = "bold #b7a1ff"
table_border_style = "#ffc284"
panel_border_style = "#ffc284"
column_output = "bold #b7a1ff"
column_value = "#b7a1ff"
bright_black = "#353147"
bright_blue = "#ffc284"
bright_cyan = "#2488ff"
bright_green = "#2dcd73"
bright_magenta = "#de8d40"
bright_red = "#d9393e"
bright_white = "#eae5ff"
bright_yellow = "#d9b76e"
normal_black = "#1f1d27"
normal_blue = "#ffc284"
normal_cyan = "#2488ff"
normal_green = "#2dcd73"
normal_magenta = "#de8d40"
normal_red = "#d9393e"
normal_white = "#b7a1ff"
normal_yellow = "#d9b76e"
cursor_cursor = "#ff9839"
cursor_text = "#1f1d27"
table_show_lines = false
table_box = "SIMPLE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#353147"
blue = "#ffc284"
cyan = "#2488ff"
green = "#2dcd73"
magenta = "#de8d40"
red = "#d9393e"
white = "#eae5ff"
yellow = "#d9b76e"

[colors.cursor]
cursor = "#ff9839"
text = "#1f1d27"

[colors.normal]
black = "#1f1d27"
blue = "#ffc284"
cyan = "#2488ff"
green = "#2dcd73"
magenta = "#de8d40"
red = "#d9393e"
white = "#b7a1ff"
yellow = "#d9b76e"

[colors.primary]
background = "#1f1d27"
foreground = "#b7a1ff"

[colors.selection]
background = "#353147"
text = "#b7a2ff"
