[rich]
panel_style = "on #181818"
table_header_style = "bold #000000 on #b5d5ff"
table_title_style = "bold #efefef"
table_border_style = "#0955ff"
panel_border_style = "#0955ff"
column_output = "bold #efefef"
column_value = "#efefef"
bright_black = "#4b4b4b"
bright_blue = "#0955ff"
bright_cyan = "#3ea8fc"
bright_green = "#6bc219"
bright_magenta = "#fb0050"
bright_red = "#fc1c18"
bright_white = "#8c00ec"
bright_yellow = "#fec80e"
normal_black = "#242424"
normal_blue = "#063b8c"
normal_cyan = "#2595e1"
normal_green = "#5aa513"
normal_magenta = "#e40038"
normal_red = "#d71c15"
normal_white = "#efefef"
normal_yellow = "#fdb40c"
cursor_cursor = "#bbbbbb"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#4b4b4b"
blue = "#0955ff"
cyan = "#3ea8fc"
green = "#6bc219"
magenta = "#fb0050"
red = "#fc1c18"
white = "#8c00ec"
yellow = "#fec80e"

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.normal]
black = "#242424"
blue = "#063b8c"
cyan = "#2595e1"
green = "#5aa513"
magenta = "#e40038"
red = "#d71c15"
white = "#efefef"
yellow = "#fdb40c"

[colors.primary]
background = "#181818"
foreground = "#efefef"

[colors.selection]
background = "#b5d5ff"
text = "#000000"
