[rich]
panel_style = "on #292f33"
table_header_style = "bold #ffffff on #efb8ac"
table_title_style = "bold #dbdae0"
table_border_style = "#7c85c4"
panel_border_style = "#7c85c4"
column_output = "bold #dbdae0"
column_value = "#dbdae0"
bright_black = "#092028"
bright_blue = "#7c85c4"
bright_cyan = "#819090"
bright_green = "#d4605a"
bright_magenta = "#5c5db2"
bright_red = "#d4605a"
bright_white = "#fcf4df"
bright_yellow = "#a86671"
normal_black = "#292f33"
normal_blue = "#2e78c2"
normal_cyan = "#309186"
normal_green = "#edb8ac"
normal_magenta = "#c0236f"
normal_red = "#cb1e2d"
normal_white = "#eae3ce"
normal_yellow = "#b7ab9b"
cursor_cursor = "#d4605a"
cursor_text = "#fefff2"
table_show_lines = false
table_box = "HEAVY"
panel_padding = [ 1, 1,]
panel_title_align = "right"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#092028"
blue = "#7c85c4"
cyan = "#819090"
green = "#d4605a"
magenta = "#5c5db2"
red = "#d4605a"
white = "#fcf4df"
yellow = "#a86671"

[colors.cursor]
cursor = "#d4605a"
text = "#fefff2"

[colors.normal]
black = "#292f33"
blue = "#2e78c2"
cyan = "#309186"
green = "#edb8ac"
magenta = "#c0236f"
red = "#cb1e2d"
white = "#eae3ce"
yellow = "#b7ab9b"

[colors.primary]
background = "#292f33"
foreground = "#dbdae0"

[colors.selection]
background = "#efb8ac"
text = "#ffffff"
