[rich]
panel_style = "on #1d1f21"
table_header_style = "bold #ffffff on #2b2a24"
table_title_style = "bold #b8dbef"
table_border_style = "#61b9d0"
panel_border_style = "#61b9d0"
column_output = "bold #b8dbef"
column_value = "#b8dbef"
bright_black = "#1d1d19"
bright_blue = "#61b9d0"
bright_cyan = "#d63865"
bright_green = "#a7d42c"
bright_magenta = "#695abc"
bright_red = "#d22a24"
bright_white = "#ffffff"
bright_yellow = "#ff8949"
normal_black = "#1d1d19"
normal_blue = "#5096be"
normal_cyan = "#d63865"
normal_green = "#9fd364"
normal_magenta = "#695abc"
normal_red = "#f18339"
normal_white = "#ffffff"
normal_yellow = "#f4ef6d"
cursor_cursor = "#708284"
cursor_text = "#002831"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 0, 2,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#1d1d19"
blue = "#61b9d0"
cyan = "#d63865"
green = "#a7d42c"
magenta = "#695abc"
red = "#d22a24"
white = "#ffffff"
yellow = "#ff8949"

[colors.cursor]
cursor = "#708284"
text = "#002831"

[colors.normal]
black = "#1d1d19"
blue = "#5096be"
cyan = "#d63865"
green = "#9fd364"
magenta = "#695abc"
red = "#f18339"
white = "#ffffff"
yellow = "#f4ef6d"

[colors.primary]
background = "#1d1f21"
foreground = "#b8dbef"

[colors.selection]
background = "#2b2a24"
text = "#ffffff"
