[rich]
panel_style = "on #1c1b1a"
table_header_style = "bold #4385be on #cecdc3"
table_title_style = "bold #cecdc3"
table_border_style = "#4385be"
panel_border_style = "#4385be"
column_output = "bold #cecdc3"
column_value = "#cecdc3"
bright_black = "#575653"
bright_blue = "#4385be"
bright_cyan = "#3aa99f"
bright_green = "#879a39"
bright_magenta = "#ce5d97"
bright_red = "#d14d41"
bright_white = "#cecdc3"
bright_yellow = "#d0a215"
normal_black = "#1c1b1a"
normal_blue = "#4385be"
normal_cyan = "#3aa99f"
normal_green = "#879a39"
normal_magenta = "#ce5d97"
normal_red = "#d14d41"
normal_white = "#b7b5ac"
normal_yellow = "#d0a215"
cursor_cursor = "#cecdc3"
cursor_text = "#1c1b1a"
table_show_lines = false
table_box = "MINIMAL"
panel_padding = [ 0, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#575653"
blue = "#4385be"
cyan = "#3aa99f"
green = "#879a39"
magenta = "#ce5d97"
red = "#d14d41"
white = "#cecdc3"
yellow = "#d0a215"

[colors.cursor]
cursor = "#cecdc3"
text = "#1c1b1a"

[colors.normal]
black = "#1c1b1a"
blue = "#4385be"
cyan = "#3aa99f"
green = "#879a39"
magenta = "#ce5d97"
red = "#d14d41"
white = "#b7b5ac"
yellow = "#d0a215"

[colors.primary]
background = "#1c1b1a"
foreground = "#cecdc3"

[colors.selection]
background = "#cecdc3"
text = "#4385be"
