[rich]
panel_style = "on #051519"
table_header_style = "bold #ffffff on #4d4d4d"
table_title_style = "bold #e2d8cd"
table_border_style = "#39a7a2"
panel_border_style = "#39a7a2"
column_output = "bold #e2d8cd"
column_value = "#e2d8cd"
bright_black = "#3d3d3d"
bright_blue = "#39a7a2"
bright_cyan = "#6096bf"
bright_green = "#6bb48d"
bright_magenta = "#7e62b3"
bright_red = "#fb3d66"
bright_white = "#e2d8cd"
bright_yellow = "#30c85a"
normal_black = "#333333"
normal_blue = "#8ed0ce"
normal_cyan = "#31658c"
normal_green = "#92d3a2"
normal_magenta = "#5e468c"
normal_red = "#f8818e"
normal_white = "#e2d8cd"
normal_yellow = "#1a8e63"
cursor_cursor = "#9e9ecb"
cursor_text = "#000000"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 0, 2,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#3d3d3d"
blue = "#39a7a2"
cyan = "#6096bf"
green = "#6bb48d"
magenta = "#7e62b3"
red = "#fb3d66"
white = "#e2d8cd"
yellow = "#30c85a"

[colors.cursor]
cursor = "#9e9ecb"
text = "#000000"

[colors.normal]
black = "#333333"
blue = "#8ed0ce"
cyan = "#31658c"
green = "#92d3a2"
magenta = "#5e468c"
red = "#f8818e"
white = "#e2d8cd"
yellow = "#1a8e63"

[colors.primary]
background = "#051519"
foreground = "#e2d8cd"

[colors.selection]
background = "#4d4d4d"
text = "#ffffff"
