[rich]
panel_style = "on #071317"
table_header_style = "bold #ddeeff on #071317"
table_title_style = "bold #ddeeff"
table_border_style = "#3377ff"
panel_border_style = "#3377ff"
column_output = "bold #ddeeff"
column_value = "#ddeeff"
bright_black = "#556677"
bright_blue = "#3377ff"
bright_cyan = "#33ddff"
bright_green = "#33ff11"
bright_magenta = "#aa77ff"
bright_red = "#ff1133"
bright_white = "#bbccdd"
bright_yellow = "#ffdd33"
normal_black = "#223344"
normal_blue = "#2255cc"
normal_cyan = "#22bbdd"
normal_green = "#33aa11"
normal_magenta = "#7755aa"
normal_red = "#aa1122"
normal_white = "#8899aa"
normal_yellow = "#ccaa22"
cursor_cursor = "#ddeeff"
cursor_text = "#071317"
table_show_lines = false
table_box = "HEAVY"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#556677"
blue = "#3377ff"
cyan = "#33ddff"
green = "#33ff11"
magenta = "#aa77ff"
red = "#ff1133"
white = "#bbccdd"
yellow = "#ffdd33"

[colors.cursor]
cursor = "#ddeeff"
text = "#071317"

[colors.normal]
black = "#223344"
blue = "#2255cc"
cyan = "#22bbdd"
green = "#33aa11"
magenta = "#7755aa"
red = "#aa1122"
white = "#8899aa"
yellow = "#ccaa22"

[colors.primary]
background = "#071317"
foreground = "#ddeeff"

[colors.selection]
background = "#071317"
text = "#ddeeff"
