[rich]
panel_style = "on #121212"
table_header_style = "bold #b6bbc0 on #453b39"
table_title_style = "bold #a0a0a0"
table_border_style = "#66d9ef"
panel_border_style = "#66d9ef"
column_output = "bold #a0a0a0"
column_value = "#a0a0a0"
bright_black = "#505354"
bright_blue = "#66d9ef"
bright_cyan = "#a3babf"
bright_green = "#beed5f"
bright_magenta = "#9e6ffe"
bright_red = "#ff669d"
bright_white = "#f8f8f2"
bright_yellow = "#e6db74"
normal_black = "#1b1d1e"
normal_blue = "#66d9ef"
normal_cyan = "#5e7175"
normal_green = "#a6e22e"
normal_magenta = "#9e6ffe"
normal_red = "#f92672"
normal_white = "#ccccc6"
normal_yellow = "#fd971f"
cursor_cursor = "#bbbbbb"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 2, 2,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#505354"
blue = "#66d9ef"
cyan = "#a3babf"
green = "#beed5f"
magenta = "#9e6ffe"
red = "#ff669d"
white = "#f8f8f2"
yellow = "#e6db74"

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.normal]
black = "#1b1d1e"
blue = "#66d9ef"
cyan = "#5e7175"
green = "#a6e22e"
magenta = "#9e6ffe"
red = "#f92672"
white = "#ccccc6"
yellow = "#fd971f"

[colors.primary]
background = "#121212"
foreground = "#a0a0a0"

[colors.selection]
background = "#453b39"
text = "#b6bbc0"
