[rich]
panel_style = "on #020f01"
table_header_style = "bold #fdfdfd on #d4ffc1"
table_title_style = "bold #16b10e"
table_border_style = "#19e20e"
panel_border_style = "#19e20e"
column_output = "bold #16b10e"
column_value = "#16b10e"
bright_black = "#001510"
bright_blue = "#19e20e"
bright_cyan = "#19e20e"
bright_green = "#19e20e"
bright_magenta = "#19e20e"
bright_red = "#19e20e"
bright_white = "#fefefe"
bright_yellow = "#19e20e"
normal_black = "#001f0b"
normal_blue = "#15d00d"
normal_cyan = "#15d00d"
normal_green = "#15d00d"
normal_magenta = "#15d00d"
normal_red = "#15d00d"
normal_white = "#fafafa"
normal_yellow = "#15d00d"
cursor_cursor = "#15d00d"
cursor_text = "#ffffff"
table_show_lines = false
table_box = "MINIMAL"
panel_padding = [ 1, 1,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#001510"
blue = "#19e20e"
cyan = "#19e20e"
green = "#19e20e"
magenta = "#19e20e"
red = "#19e20e"
white = "#fefefe"
yellow = "#19e20e"

[colors.cursor]
cursor = "#15d00d"
text = "#ffffff"

[colors.normal]
black = "#001f0b"
blue = "#15d00d"
cyan = "#15d00d"
green = "#15d00d"
magenta = "#15d00d"
red = "#15d00d"
white = "#fafafa"
yellow = "#15d00d"

[colors.primary]
background = "#020f01"
foreground = "#16b10e"

[colors.selection]
background = "#d4ffc1"
text = "#fdfdfd"
