[rich]
panel_style = "on #161821"
table_header_style = "bold #161821 on #c6c8d1"
table_title_style = "bold #c6c8d1"
table_border_style = "#91acd1"
panel_border_style = "#91acd1"
column_output = "bold #c6c8d1"
column_value = "#c6c8d1"
bright_black = "#6b7089"
bright_blue = "#91acd1"
bright_cyan = "#95c4ce"
bright_green = "#c0ca8e"
bright_magenta = "#ada0d3"
bright_red = "#e98989"
bright_white = "#d2d4de"
bright_yellow = "#e9b189"
normal_black = "#1e2132"
normal_blue = "#84a0c6"
normal_cyan = "#89b8c2"
normal_green = "#b4be82"
normal_magenta = "#a093c7"
normal_red = "#e27878"
normal_white = "#c6c8d1"
normal_yellow = "#e2a478"
cursor_cursor = "#c6c8d1"
cursor_text = "#161821"
table_show_lines = false
table_box = "SQUARE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#6b7089"
blue = "#91acd1"
cyan = "#95c4ce"
green = "#c0ca8e"
magenta = "#ada0d3"
red = "#e98989"
white = "#d2d4de"
yellow = "#e9b189"

[colors.cursor]
cursor = "#c6c8d1"
text = "#161821"

[colors.normal]
black = "#1e2132"
blue = "#84a0c6"
cyan = "#89b8c2"
green = "#b4be82"
magenta = "#a093c7"
red = "#e27878"
white = "#c6c8d1"
yellow = "#e2a478"

[colors.primary]
background = "#161821"
foreground = "#c6c8d1"

[colors.selection]
background = "#c6c8d1"
text = "#161821"
