[rich]
panel_style = "on #202020"
table_header_style = "bold #ffffff on #44475a"
table_title_style = "bold #adadad"
table_border_style = "#6c9ced"
panel_border_style = "#6c9ced"
column_output = "bold #adadad"
column_value = "#adadad"
bright_black = "#ffffff"
bright_blue = "#6c9ced"
bright_cyan = "#248887"
bright_green = "#98b61c"
bright_magenta = "#fc7eff"
bright_red = "#fc7072"
bright_white = "#181818"
bright_yellow = "#ffff0b"
normal_black = "#adadad"
normal_blue = "#437ee7"
normal_cyan = "#248887"
normal_green = "#98b61c"
normal_magenta = "#9d74b0"
normal_red = "#fc5256"
normal_white = "#181818"
normal_yellow = "#ccb444"
cursor_cursor = "#bbbbbb"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#ffffff"
blue = "#6c9ced"
cyan = "#248887"
green = "#98b61c"
magenta = "#fc7eff"
red = "#fc7072"
white = "#181818"
yellow = "#ffff0b"

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.normal]
black = "#adadad"
blue = "#437ee7"
cyan = "#248887"
green = "#98b61c"
magenta = "#9d74b0"
red = "#fc5256"
white = "#181818"
yellow = "#ccb444"

[colors.primary]
background = "#202020"
foreground = "#adadad"

[colors.selection]
background = "#44475a"
text = "#ffffff"
