[rich]
panel_style = "on #323232"
table_header_style = "bold #000000 on #5b5b5b"
table_title_style = "bold #ffffff"
table_border_style = "#5eb7f7"
panel_border_style = "#5eb7f7"
column_output = "bold #ffffff"
column_value = "#ffffff"
bright_black = "#535353"
bright_blue = "#5eb7f7"
bright_cyan = "#dcf4ff"
bright_green = "#9dff91"
bright_magenta = "#ff9dff"
bright_red = "#f07070"
bright_white = "#ffffff"
bright_yellow = "#ffe48b"
normal_black = "#323232"
normal_blue = "#4099ff"
normal_cyan = "#bed6ff"
normal_green = "#7fe173"
normal_magenta = "#f680ff"
normal_red = "#d25252"
normal_white = "#eeeeec"
normal_yellow = "#ffc66d"
cursor_cursor = "#d6d6d6"
cursor_text = "#000000"
table_show_lines = true
table_box = "SIMPLE"
panel_padding = [ 1, 2,]
panel_title_align = "left"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#535353"
blue = "#5eb7f7"
cyan = "#dcf4ff"
green = "#9dff91"
magenta = "#ff9dff"
red = "#f07070"
white = "#ffffff"
yellow = "#ffe48b"

[colors.cursor]
cursor = "#d6d6d6"
text = "#000000"

[colors.normal]
black = "#323232"
blue = "#4099ff"
cyan = "#bed6ff"
green = "#7fe173"
magenta = "#f680ff"
red = "#d25252"
white = "#eeeeec"
yellow = "#ffc66d"

[colors.primary]
background = "#323232"
foreground = "#ffffff"

[colors.selection]
background = "#5b5b5b"
text = "#000000"
