[rich]
panel_style = "on #002b36"
table_header_style = "bold #93a1a1 on #073642"
table_title_style = "bold #839496"
table_border_style = "#839496"
panel_border_style = "#839496"
column_output = "bold #839496"
column_value = "#839496"
bright_black = "#002b36"
bright_blue = "#839496"
bright_cyan = "#93a1a1"
bright_green = "#586e75"
bright_magenta = "#6c71c4"
bright_red = "#cb4b16"
bright_white = "#fdf6e3"
bright_yellow = "#657b83"
normal_black = "#073642"
normal_blue = "#268bd2"
normal_cyan = "#2aa198"
normal_green = "#859900"
normal_magenta = "#d33682"
normal_red = "#dc322f"
normal_white = "#eee8d5"
normal_yellow = "#b58900"
cursor_cursor = "#839496"
cursor_text = "#073642"
table_show_lines = true
table_box = "HEAVY"
panel_padding = [ 1, 2,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#073642"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[colors.selection]
background = "#073642"
text = "#93a1a1"
