[rich]
panel_style = "on #2c1d16"
table_header_style = "bold #ffffff on #af8d21"
table_title_style = "bold #ffcc2f"
table_border_style = "#0000ff"
panel_border_style = "#0000ff"
column_output = "bold #ffcc2f"
column_value = "#ffcc2f"
bright_black = "#666666"
bright_blue = "#0000ff"
bright_cyan = "#00e5e5"
bright_green = "#86a93e"
bright_magenta = "#e500e5"
bright_red = "#e50000"
bright_white = "#e5e5e5"
bright_yellow = "#e5e500"
normal_black = "#2c1d16"
normal_blue = "#246eb2"
normal_cyan = "#00acee"
normal_green = "#2baf2b"
normal_magenta = "#d05ec1"
normal_red = "#ef5734"
normal_white = "#bfbfbf"
normal_yellow = "#bebf00"
cursor_cursor = "#23ff18"
cursor_text = "#ff0018"
table_show_lines = true
table_box = "SQUARE"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#666666"
blue = "#0000ff"
cyan = "#00e5e5"
green = "#86a93e"
magenta = "#e500e5"
red = "#e50000"
white = "#e5e5e5"
yellow = "#e5e500"

[colors.cursor]
cursor = "#23ff18"
text = "#ff0018"

[colors.normal]
black = "#2c1d16"
blue = "#246eb2"
cyan = "#00acee"
green = "#2baf2b"
magenta = "#d05ec1"
red = "#ef5734"
white = "#bfbfbf"
yellow = "#bebf00"

[colors.primary]
background = "#2c1d16"
foreground = "#ffcc2f"

[colors.selection]
background = "#af8d21"
text = "#ffffff"
