[rich]
panel_style = "on #202020"
table_header_style = "bold #adadad on #1a3272"
table_title_style = "bold #adadad"
table_border_style = "#6d9df1"
panel_border_style = "#6d9df1"
column_output = "bold #adadad"
column_value = "#adadad"
bright_black = "#555555"
bright_blue = "#6d9df1"
bright_cyan = "#60d3d1"
bright_green = "#67ff4f"
bright_magenta = "#fb82ff"
bright_red = "#fb7172"
bright_white = "#eeeeee"
bright_yellow = "#ffff00"
normal_black = "#000000"
normal_blue = "#4581eb"
normal_cyan = "#33c2c1"
normal_green = "#126e00"
normal_magenta = "#fa54ff"
normal_red = "#fa5355"
normal_white = "#adadad"
normal_yellow = "#c2c300"
cursor_cursor = "#ffffff"
cursor_text = "#000000"
table_show_lines = true
table_box = "HEAVY"
panel_padding = [ 1, 1,]
panel_title_align = "left"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#555555"
blue = "#6d9df1"
cyan = "#60d3d1"
green = "#67ff4f"
magenta = "#fb82ff"
red = "#fb7172"
white = "#eeeeee"
yellow = "#ffff00"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#4581eb"
cyan = "#33c2c1"
green = "#126e00"
magenta = "#fa54ff"
red = "#fa5355"
white = "#adadad"
yellow = "#c2c300"

[colors.primary]
background = "#202020"
foreground = "#adadad"

[colors.selection]
background = "#1a3272"
text = "#adadad"
