[rich]
panel_style = "on #0e100a"
table_header_style = "bold #000000 on #9ba787"
table_title_style = "bold #f7f7f7"
table_border_style = "#97a4f7"
panel_border_style = "#97a4f7"
column_output = "bold #f7f7f7"
column_value = "#f7f7f7"
bright_black = "#5a5a5a"
bright_blue = "#97a4f7"
bright_cyan = "#68f2e0"
bright_green = "#6ce05c"
bright_magenta = "#c495f0"
bright_red = "#f01578"
bright_white = "#ffffff"
bright_yellow = "#f3f79e"
normal_black = "#4d4d4d"
normal_blue = "#3449d1"
normal_cyan = "#0798ab"
normal_green = "#29cf13"
normal_magenta = "#8400ff"
normal_red = "#c70031"
normal_white = "#e2d1e3"
normal_yellow = "#d8e30e"
cursor_cursor = "#9fda9c"
cursor_text = "#000000"
table_show_lines = false
table_box = "ROUNDED"
panel_padding = [ 1, 1,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#5a5a5a"
blue = "#97a4f7"
cyan = "#68f2e0"
green = "#6ce05c"
magenta = "#c495f0"
red = "#f01578"
white = "#ffffff"
yellow = "#f3f79e"

[colors.cursor]
cursor = "#9fda9c"
text = "#000000"

[colors.normal]
black = "#4d4d4d"
blue = "#3449d1"
cyan = "#0798ab"
green = "#29cf13"
magenta = "#8400ff"
red = "#c70031"
white = "#e2d1e3"
yellow = "#d8e30e"

[colors.primary]
background = "#0e100a"
foreground = "#f7f7f7"

[colors.selection]
background = "#9ba787"
text = "#000000"
