[rich]
panel_style = "on #050014"
table_header_style = "bold #8c91fa on #37323c"
table_title_style = "bold #736e7d"
table_border_style = "#8e87e0"
panel_border_style = "#8e87e0"
column_output = "bold #736e7d"
column_value = "#736e7d"
bright_black = "#372d46"
bright_blue = "#8e87e0"
bright_cyan = "#9ad4e0"
bright_green = "#52e0c4"
bright_magenta = "#a776e0"
bright_red = "#e05167"
bright_white = "#8c91fa"
bright_yellow = "#e0c386"
normal_black = "#230046"
normal_blue = "#4f4a7f"
normal_cyan = "#58777f"
normal_green = "#337e6f"
normal_magenta = "#5a3f7f"
normal_red = "#7d1625"
normal_white = "#736e7d"
normal_yellow = "#7f6f49"
cursor_cursor = "#8c91fa"
cursor_text = "#050014"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#372d46"
blue = "#8e87e0"
cyan = "#9ad4e0"
green = "#52e0c4"
magenta = "#a776e0"
red = "#e05167"
white = "#8c91fa"
yellow = "#e0c386"

[colors.cursor]
cursor = "#8c91fa"
text = "#050014"

[colors.normal]
black = "#230046"
blue = "#4f4a7f"
cyan = "#58777f"
green = "#337e6f"
magenta = "#5a3f7f"
red = "#7d1625"
white = "#736e7d"
yellow = "#7f6f49"

[colors.primary]
background = "#050014"
foreground = "#736e7d"

[colors.selection]
background = "#37323c"
text = "#8c91fa"
