[rich]
panel_style = "on #0f111a"
table_header_style = "bold #8f93a2 on #1f2233"
table_title_style = "bold #8f93a2"
table_border_style = "#82aaff"
panel_border_style = "#82aaff"
column_output = "bold #8f93a2"
column_value = "#8f93a2"
bright_black = "#546e7a"
bright_blue = "#82aaff"
bright_cyan = "#89ddff"
bright_green = "#c3e88d"
bright_magenta = "#c792ea"
bright_red = "#ff5370"
bright_white = "#ffffff"
bright_yellow = "#ffcb6b"
normal_black = "#546e7a"
normal_blue = "#82aaff"
normal_cyan = "#89ddff"
normal_green = "#c3e88d"
normal_magenta = "#c792ea"
normal_red = "#ff5370"
normal_white = "#ffffff"
normal_yellow = "#ffcb6b"
cursor_cursor = "#ffcc00"
cursor_text = "#0f111a"
table_show_lines = false
table_box = "MINIMAL"
panel_padding = [ 1, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#546e7a"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.cursor]
cursor = "#ffcc00"
text = "#0f111a"

[colors.normal]
black = "#546e7a"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#ff5370"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#0f111a"
foreground = "#8f93a2"

[colors.selection]
background = "#1f2233"
text = "#8f93a2"
