[rich]
panel_style = "on #0f191c"
table_header_style = "bold #00ff87 on #18282e"
table_title_style = "bold #426644"
table_border_style = "#4f7e7e"
panel_border_style = "#4f7e7e"
column_output = "bold #426644"
column_value = "#426644"
bright_black = "#688060"
bright_blue = "#4f7e7e"
bright_cyan = "#c1ff8a"
bright_green = "#90d762"
bright_magenta = "#11ff25"
bright_red = "#2fc079"
bright_white = "#678c61"
bright_yellow = "#faff00"
normal_black = "#0f191c"
normal_blue = "#3f5242"
normal_cyan = "#50b45a"
normal_green = "#82d967"
normal_magenta = "#409931"
normal_red = "#23755a"
normal_white = "#507350"
normal_yellow = "#ffd700"
cursor_cursor = "#384545"
cursor_text = "#00ff00"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#688060"
blue = "#4f7e7e"
cyan = "#c1ff8a"
green = "#90d762"
magenta = "#11ff25"
red = "#2fc079"
white = "#678c61"
yellow = "#faff00"

[colors.cursor]
cursor = "#384545"
text = "#00ff00"

[colors.normal]
black = "#0f191c"
blue = "#3f5242"
cyan = "#50b45a"
green = "#82d967"
magenta = "#409931"
red = "#23755a"
white = "#507350"
yellow = "#ffd700"

[colors.primary]
background = "#0f191c"
foreground = "#426644"

[colors.selection]
background = "#18282e"
text = "#00ff87"
