[rich]
panel_style = "on #1a1a1a"
table_header_style = "bold #c0af8c on #2d2d2d"
table_title_style = "bold #dadada"
table_border_style = "#5a6599"
panel_border_style = "#5a6599"
column_output = "bold #dadada"
column_value = "#dadada"
bright_black = "#5b5b5b"
bright_blue = "#5a6599"
bright_cyan = "#74a39e"
bright_green = "#828040"
bright_magenta = "#9c6995"
bright_red = "#c95954"
bright_white = "#ffffff"
bright_yellow = "#a6794c"
normal_black = "#1a1a1a"
normal_blue = "#a8a1be"
normal_cyan = "#c0af8c"
normal_green = "#b3b393"
normal_magenta = "#b39fb0"
normal_red = "#d29393"
normal_white = "#dadada"
normal_yellow = "#cbaa89"
cursor_cursor = "#bfad9e"
cursor_text = "#1a1a1a"
table_show_lines = false
table_box = "HEAVY"
panel_padding = [ 2, 2,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#5b5b5b"
blue = "#5a6599"
cyan = "#74a39e"
green = "#828040"
magenta = "#9c6995"
red = "#c95954"
white = "#ffffff"
yellow = "#a6794c"

[colors.cursor]
cursor = "#bfad9e"
text = "#1a1a1a"

[colors.normal]
black = "#1a1a1a"
blue = "#a8a1be"
cyan = "#c0af8c"
green = "#b3b393"
magenta = "#b39fb0"
red = "#d29393"
white = "#dadada"
yellow = "#cbaa89"

[colors.primary]
background = "#1a1a1a"
foreground = "#dadada"

[colors.selection]
background = "#2d2d2d"
text = "#c0af8c"
