[rich]
panel_style = "on #120b0d"
table_header_style = "bold #120b0d on #f7d66a"
table_title_style = "bold #f7d66a"
table_border_style = "#9eb2b4"
panel_border_style = "#9eb2b4"
column_output = "bold #f7d66a"
column_value = "#f7d66a"
bright_black = "#874228"
bright_blue = "#9eb2b4"
bright_cyan = "#8acd8f"
bright_green = "#b4b264"
bright_magenta = "#ff5b6a"
bright_red = "#ff4331"
bright_white = "#ffe598"
bright_yellow = "#ff9566"
normal_black = "#351b0e"
normal_blue = "#515c5d"
normal_cyan = "#588056"
normal_green = "#636232"
normal_magenta = "#9b1d29"
normal_red = "#9b291c"
normal_white = "#f7d75c"
normal_yellow = "#c36e28"
cursor_cursor = "#c46c32"
cursor_text = "#120b0d"
table_show_lines = false
table_box = "ROUNDED"
panel_padding = [ 1, 2,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#874228"
blue = "#9eb2b4"
cyan = "#8acd8f"
green = "#b4b264"
magenta = "#ff5b6a"
red = "#ff4331"
white = "#ffe598"
yellow = "#ff9566"

[colors.cursor]
cursor = "#c46c32"
text = "#120b0d"

[colors.normal]
black = "#351b0e"
blue = "#515c5d"
cyan = "#588056"
green = "#636232"
magenta = "#9b1d29"
red = "#9b291c"
white = "#f7d75c"
yellow = "#c36e28"

[colors.primary]
background = "#120b0d"
foreground = "#f7d66a"

[colors.selection]
background = "#f7d66a"
text = "#120b0d"
