[rich]
panel_style = "on #1a1a1a"
table_header_style = "bold #c4c5b5 on #343434"
table_title_style = "bold #c4c5b5"
table_border_style = "#9d65ff"
panel_border_style = "#9d65ff"
column_output = "bold #c4c5b5"
column_value = "#c4c5b5"
bright_black = "#625e4c"
bright_blue = "#9d65ff"
bright_cyan = "#58d1eb"
bright_green = "#98e024"
bright_magenta = "#f4005f"
bright_red = "#f4005f"
bright_white = "#f6f6ef"
bright_yellow = "#e0d561"
normal_black = "#1a1a1a"
normal_blue = "#9d65ff"
normal_cyan = "#58d1eb"
normal_green = "#98e024"
normal_magenta = "#f4005f"
normal_red = "#f4005f"
normal_white = "#c4c5b5"
normal_yellow = "#fa8419"
cursor_cursor = "#f6f7ec"
cursor_text = "#c4c5b5"
table_show_lines = false
table_box = "SQUARE"
panel_padding = [ 0, 2,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#625e4c"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#f6f6ef"
yellow = "#e0d561"

[colors.cursor]
cursor = "#f6f7ec"
text = "#c4c5b5"

[colors.normal]
black = "#1a1a1a"
blue = "#9d65ff"
cyan = "#58d1eb"
green = "#98e024"
magenta = "#f4005f"
red = "#f4005f"
white = "#c4c5b5"
yellow = "#fa8419"

[colors.primary]
background = "#1a1a1a"
foreground = "#c4c5b5"

[colors.selection]
background = "#343434"
text = "#c4c5b5"
