[rich]
panel_style = "on #0f191f"
table_header_style = "bold #c6d5cf on #3a3e3d"
table_title_style = "bold #c6d5cf"
table_border_style = "#92a0e2"
panel_border_style = "#92a0e2"
column_output = "bold #c6d5cf"
column_value = "#c6d5cf"
bright_black = "#263945"
bright_blue = "#92a0e2"
bright_cyan = "#65b8c1"
bright_green = "#a0ff85"
bright_magenta = "#cf86c1"
bright_red = "#e8838f"
bright_white = "#98a39e"
bright_yellow = "#d68c67"
normal_black = "#0f191f"
normal_blue = "#8190d4"
normal_cyan = "#66a5ad"
normal_green = "#90ff6b"
normal_magenta = "#b279a7"
normal_red = "#de6e7c"
normal_white = "#c6d5cf"
normal_yellow = "#b77e64"
cursor_cursor = "#ceddd7"
cursor_text = "#0f191f"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 0, 2,]
panel_title_align = "center"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#263945"
blue = "#92a0e2"
cyan = "#65b8c1"
green = "#a0ff85"
magenta = "#cf86c1"
red = "#e8838f"
white = "#98a39e"
yellow = "#d68c67"

[colors.cursor]
cursor = "#ceddd7"
text = "#0f191f"

[colors.normal]
black = "#0f191f"
blue = "#8190d4"
cyan = "#66a5ad"
green = "#90ff6b"
magenta = "#b279a7"
red = "#de6e7c"
white = "#c6d5cf"
yellow = "#b77e64"

[colors.primary]
background = "#0f191f"
foreground = "#c6d5cf"

[colors.selection]
background = "#3a3e3d"
text = "#c6d5cf"
