[rich]
panel_style = "on #14161a"
table_header_style = "bold #08d2cf on #0013ff"
table_title_style = "bold #00fffc"
table_border_style = "#3c40cb"
panel_border_style = "#3c40cb"
column_output = "bold #00fffc"
column_value = "#00fffc"
bright_black = "#686868"
bright_blue = "#3c40cb"
bright_cyan = "#88fffe"
bright_green = "#75ff88"
bright_magenta = "#f15be5"
bright_red = "#ff5a5a"
bright_white = "#ffffff"
bright_yellow = "#fffd96"
normal_black = "#000000"
normal_blue = "#0208cb"
normal_cyan = "#00fffc"
normal_green = "#5ffa74"
normal_magenta = "#f924e7"
normal_red = "#ff3045"
normal_white = "#c7c7c7"
normal_yellow = "#fffc7e"
cursor_cursor = "#c7c7c7"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 1, 1,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#686868"
blue = "#3c40cb"
cyan = "#88fffe"
green = "#75ff88"
magenta = "#f15be5"
red = "#ff5a5a"
white = "#ffffff"
yellow = "#fffd96"

[colors.cursor]
cursor = "#c7c7c7"
text = "#ffffff"

[colors.normal]
black = "#000000"
blue = "#0208cb"
cyan = "#00fffc"
green = "#5ffa74"
magenta = "#f924e7"
red = "#ff3045"
white = "#c7c7c7"
yellow = "#fffc7e"

[colors.primary]
background = "#14161a"
foreground = "#00fffc"

[colors.selection]
background = "#0013ff"
text = "#08d2cf"
