[rich]
panel_style = "on #000000"
table_header_style = "bold #000000 on #b5d5ff"
table_title_style = "bold #bbbbbb"
table_border_style = "#5555ff"
panel_border_style = "#5555ff"
column_output = "bold #bbbbbb"
column_value = "#bbbbbb"
bright_black = "#555555"
bright_blue = "#5555ff"
bright_cyan = "#55ffff"
bright_green = "#55ff55"
bright_magenta = "#ff55ff"
bright_red = "#ff5555"
bright_white = "#ffffff"
bright_yellow = "#ffff55"
normal_black = "#4c4c4c"
normal_blue = "#276bd8"
normal_cyan = "#00dadf"
normal_green = "#5fde8f"
normal_magenta = "#bb00bb"
normal_red = "#bb0000"
normal_white = "#bbbbbb"
normal_yellow = "#f3f167"
cursor_cursor = "#bbbbbb"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "SIMPLE"
panel_padding = [ 0, 2,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#55ffff"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.normal]
black = "#4c4c4c"
blue = "#276bd8"
cyan = "#00dadf"
green = "#5fde8f"
magenta = "#bb00bb"
red = "#bb0000"
white = "#bbbbbb"
yellow = "#f3f167"

[colors.primary]
background = "#000000"
foreground = "#bbbbbb"

[colors.selection]
background = "#b5d5ff"
text = "#000000"
