[rich]
panel_style = "on #ffffff"
table_header_style = "bold #403f53 on #f2f2f2"
table_title_style = "bold #403f53"
table_border_style = "#5ca7e4"
panel_border_style = "#5ca7e4"
column_output = "bold #403f53"
column_value = "#403f53"
bright_black = "#7a8181"
bright_blue = "#5ca7e4"
bright_cyan = "#00c990"
bright_green = "#49d0c5"
bright_magenta = "#697098"
bright_red = "#f76e6e"
bright_white = "#989fb1"
bright_yellow = "#dac26b"
normal_black = "#011627"
normal_blue = "#4876d6"
normal_cyan = "#08916a"
normal_green = "#2aa298"
normal_magenta = "#403f53"
normal_red = "#d3423e"
normal_white = "#7a8181"
normal_yellow = "#daaa01"
cursor_cursor = "#403f53"
cursor_text = "#fbfbfb"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 1, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#7a8181"
blue = "#5ca7e4"
cyan = "#00c990"
green = "#49d0c5"
magenta = "#697098"
red = "#f76e6e"
white = "#989fb1"
yellow = "#dac26b"

[colors.cursor]
cursor = "#403f53"
text = "#fbfbfb"

[colors.normal]
black = "#011627"
blue = "#4876d6"
cyan = "#08916a"
green = "#2aa298"
magenta = "#403f53"
red = "#d3423e"
white = "#7a8181"
yellow = "#daaa01"

[colors.primary]
background = "#ffffff"
foreground = "#403f53"

[colors.selection]
background = "#f2f2f2"
text = "#403f53"
