[rich]
panel_style = "on #3e4251"
table_header_style = "bold #80cbc4 on #717cb4"
table_title_style = "bold #cccccc"
table_border_style = "#b4ccff"
panel_border_style = "#b4ccff"
column_output = "bold #cccccc"
column_value = "#cccccc"
bright_black = "#666666"
bright_blue = "#b4ccff"
bright_cyan = "#b8eaff"
bright_green = "#dbf1ba"
bright_magenta = "#ddbdf2"
bright_red = "#f6a9ae"
bright_white = "#999999"
bright_yellow = "#ffdfa6"
normal_black = "#000000"
normal_blue = "#82aaff"
normal_cyan = "#89ddff"
normal_green = "#c3e88d"
normal_magenta = "#c792ea"
normal_red = "#f07178"
normal_white = "#ffffff"
normal_yellow = "#ffcb6b"
cursor_cursor = "#ffcb6b"
cursor_text = "#323232"
table_show_lines = false
table_box = "HEAVY"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#666666"
blue = "#b4ccff"
cyan = "#b8eaff"
green = "#dbf1ba"
magenta = "#ddbdf2"
red = "#f6a9ae"
white = "#999999"
yellow = "#ffdfa6"

[colors.cursor]
cursor = "#ffcb6b"
text = "#323232"

[colors.normal]
black = "#000000"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#ffffff"
yellow = "#ffcb6b"

[colors.primary]
background = "#3e4251"
foreground = "#cccccc"

[colors.selection]
background = "#717cb4"
text = "#80cbc4"
