[rich]
panel_style = "on #2f1e2e"
table_header_style = "bold #a39e9b on #4f424c"
table_title_style = "bold #a39e9b"
table_border_style = "#06b6ef"
panel_border_style = "#06b6ef"
column_output = "bold #a39e9b"
column_value = "#a39e9b"
bright_black = "#776e71"
bright_blue = "#06b6ef"
bright_cyan = "#5bc4bf"
bright_green = "#48b685"
bright_magenta = "#815ba4"
bright_red = "#ef6155"
bright_white = "#e7e9db"
bright_yellow = "#fec418"
normal_black = "#2f1e2e"
normal_blue = "#06b6ef"
normal_cyan = "#5bc4bf"
normal_green = "#48b685"
normal_magenta = "#815ba4"
normal_red = "#ef6155"
normal_white = "#a39e9b"
normal_yellow = "#fec418"
cursor_cursor = "#a39e9b"
cursor_text = "#2f1e2e"
table_show_lines = false
table_box = "SIMPLE"
panel_padding = [ 1, 1,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#776e71"
blue = "#06b6ef"
cyan = "#5bc4bf"
green = "#48b685"
magenta = "#815ba4"
red = "#ef6155"
white = "#e7e9db"
yellow = "#fec418"

[colors.cursor]
cursor = "#a39e9b"
text = "#2f1e2e"

[colors.normal]
black = "#2f1e2e"
blue = "#06b6ef"
cyan = "#5bc4bf"
green = "#48b685"
magenta = "#815ba4"
red = "#ef6155"
white = "#a39e9b"
yellow = "#fec418"

[colors.primary]
background = "#2f1e2e"
foreground = "#a39e9b"

[colors.selection]
background = "#4f424c"
text = "#a39e9b"
