[rich]
panel_style = "on #000000"
table_header_style = "bold #000000 on #e6e6e6"
table_title_style = "bold #c8c8c8"
table_border_style = "#6fbce2"
panel_border_style = "#6fbce2"
column_output = "bold #c8c8c8"
column_value = "#c8c8c8"
bright_black = "#535353"
bright_blue = "#6fbce2"
bright_cyan = "#96dcdb"
bright_green = "#a3cca2"
bright_magenta = "#e586e7"
bright_red = "#e4859b"
bright_white = "#dfdfdf"
bright_yellow = "#e1e487"
normal_black = "#353535"
normal_blue = "#449fd0"
normal_cyan = "#65aaaf"
normal_green = "#89d287"
normal_magenta = "#da62dc"
normal_red = "#e74669"
normal_white = "#b4b4b4"
normal_yellow = "#dab853"
cursor_cursor = "#bbbbbb"
cursor_text = "#ffffff"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 1, 2,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#535353"
blue = "#6fbce2"
cyan = "#96dcdb"
green = "#a3cca2"
magenta = "#e586e7"
red = "#e4859b"
white = "#dfdfdf"
yellow = "#e1e487"

[colors.cursor]
cursor = "#bbbbbb"
text = "#ffffff"

[colors.normal]
black = "#353535"
blue = "#449fd0"
cyan = "#65aaaf"
green = "#89d287"
magenta = "#da62dc"
red = "#e74669"
white = "#b4b4b4"
yellow = "#dab853"

[colors.primary]
background = "#000000"
foreground = "#c8c8c8"

[colors.selection]
background = "#e6e6e6"
text = "#000000"
