[rich]
panel_style = "on #1c1c1c"
table_header_style = "bold #ffffff on #4d4d4d"
table_title_style = "bold #d0d0d0"
table_border_style = "#a1bdce"
panel_border_style = "#a1bdce"
column_output = "bold #d0d0d0"
column_value = "#d0d0d0"
bright_black = "#4a4845"
bright_blue = "#a1bdce"
bright_cyan = "#b1e7dd"
bright_green = "#afbea2"
bright_magenta = "#d7beda"
bright_red = "#d78787"
bright_white = "#efefef"
bright_yellow = "#e4c9af"
normal_black = "#2f2e2d"
normal_blue = "#7fa5bd"
normal_cyan = "#8adbb4"
normal_green = "#90a57d"
normal_magenta = "#c79ec4"
normal_red = "#a36666"
normal_white = "#d0d0d0"
normal_yellow = "#d7af87"
cursor_cursor = "#e4c9af"
cursor_text = "#000000"
table_show_lines = true
table_box = "ROUNDED"
panel_padding = [ 1, 2,]
panel_title_align = "right"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#4a4845"
blue = "#a1bdce"
cyan = "#b1e7dd"
green = "#afbea2"
magenta = "#d7beda"
red = "#d78787"
white = "#efefef"
yellow = "#e4c9af"

[colors.cursor]
cursor = "#e4c9af"
text = "#000000"

[colors.normal]
black = "#2f2e2d"
blue = "#7fa5bd"
cyan = "#8adbb4"
green = "#90a57d"
magenta = "#c79ec4"
red = "#a36666"
white = "#d0d0d0"
yellow = "#d7af87"

[colors.primary]
background = "#1c1c1c"
foreground = "#d0d0d0"

[colors.selection]
background = "#4d4d4d"
text = "#ffffff"
