[rich]
panel_style = "on #181921"
table_header_style = "bold #928374 on #ebdbb2"
table_title_style = "bold #ebdbb2"
table_border_style = "#99c6ca"
panel_border_style = "#99c6ca"
column_output = "bold #ebdbb2"
column_value = "#ebdbb2"
bright_black = "#928374"
bright_blue = "#99c6ca"
bright_cyan = "#7ec16e"
bright_green = "#b8bb26"
bright_magenta = "#d3869b"
bright_red = "#f42c3e"
bright_white = "#ebdbb2"
bright_yellow = "#fabd2f"
normal_black = "#1d2021"
normal_blue = "#458588"
normal_cyan = "#689d6a"
normal_green = "#98971a"
normal_magenta = "#b16286"
normal_red = "#cc241d"
normal_white = "#a89984"
normal_yellow = "#d79921"
cursor_cursor = "#c7c7c7"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#928374"
blue = "#99c6ca"
cyan = "#7ec16e"
green = "#b8bb26"
magenta = "#d3869b"
red = "#f42c3e"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#c7c7c7"
text = "#ffffff"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#181921"
foreground = "#ebdbb2"

[colors.selection]
background = "#ebdbb2"
text = "#928374"
