[rich]
panel_style = "on #2c3941"
table_header_style = "bold #819090 on #002831"
table_title_style = "bold #ececec"
table_border_style = "#6a8e95"
panel_border_style = "#6a8e95"
column_output = "bold #ececec"
column_value = "#ececec"
bright_black = "#5d7079"
bright_blue = "#6a8e95"
bright_cyan = "#88b2ac"
bright_green = "#66907d"
bright_magenta = "#b18a73"
bright_red = "#865f5b"
bright_white = "#ececec"
bright_yellow = "#b1a990"
normal_black = "#2c3941"
normal_blue = "#6a8e95"
normal_cyan = "#88b2ac"
normal_green = "#66907d"
normal_magenta = "#b18a73"
normal_red = "#865f5b"
normal_white = "#ececec"
normal_yellow = "#b1a990"
cursor_cursor = "#ececec"
cursor_text = "#002831"
table_show_lines = false
table_box = "ROUNDED"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#5d7079"
blue = "#6a8e95"
cyan = "#88b2ac"
green = "#66907d"
magenta = "#b18a73"
red = "#865f5b"
white = "#ececec"
yellow = "#b1a990"

[colors.cursor]
cursor = "#ececec"
text = "#002831"

[colors.normal]
black = "#2c3941"
blue = "#6a8e95"
cyan = "#88b2ac"
green = "#66907d"
magenta = "#b18a73"
red = "#865f5b"
white = "#ececec"
yellow = "#b1a990"

[colors.primary]
background = "#2c3941"
foreground = "#ececec"

[colors.selection]
background = "#002831"
text = "#819090"
