[rich]
panel_style = "on #1c153d"
table_header_style = "bold #000000 on #c1deff"
table_title_style = "bold #e41951"
table_border_style = "#6871ff"
panel_border_style = "#6871ff"
column_output = "bold #e41951"
column_value = "#e41951"
bright_black = "#686868"
bright_blue = "#6871ff"
bright_cyan = "#60fdff"
bright_green = "#5ffa68"
bright_magenta = "#bd35ec"
bright_red = "#ff6e67"
bright_white = "#ffffff"
bright_yellow = "#fffc67"
normal_black = "#101116"
normal_blue = "#0271b6"
normal_cyan = "#00c5c7"
normal_green = "#00dc84"
normal_magenta = "#ca30c7"
normal_red = "#ff0051"
normal_white = "#c7c7c7"
normal_yellow = "#faf945"
cursor_cursor = "#76ff9f"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "SIMPLE"
panel_padding = [ 1, 2,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#686868"
blue = "#6871ff"
cyan = "#60fdff"
green = "#5ffa68"
magenta = "#bd35ec"
red = "#ff6e67"
white = "#ffffff"
yellow = "#fffc67"

[colors.cursor]
cursor = "#76ff9f"
text = "#ffffff"

[colors.normal]
black = "#101116"
blue = "#0271b6"
cyan = "#00c5c7"
green = "#00dc84"
magenta = "#ca30c7"
red = "#ff0051"
white = "#c7c7c7"
yellow = "#faf945"

[colors.primary]
background = "#1c153d"
foreground = "#e41951"

[colors.selection]
background = "#c1deff"
text = "#000000"
