[rich]
panel_style = "on #09141b"
table_header_style = "bold #fee4ce on #1e4962"
table_title_style = "bold #deb88d"
table_border_style = "#1bbcdd"
panel_border_style = "#1bbcdd"
column_output = "bold #deb88d"
column_value = "#deb88d"
bright_black = "#434b53"
bright_blue = "#1bbcdd"
bright_cyan = "#87acb4"
bright_green = "#628d98"
bright_magenta = "#bbe3ee"
bright_red = "#d48678"
bright_white = "#fee4ce"
bright_yellow = "#fdd39f"
normal_black = "#17384c"
normal_blue = "#1e4950"
normal_cyan = "#50a3b5"
normal_green = "#027c9b"
normal_magenta = "#68d4f1"
normal_red = "#d15123"
normal_white = "#deb88d"
normal_yellow = "#fca02f"
cursor_cursor = "#fca02f"
cursor_text = "#08131a"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 1, 1,]
panel_title_align = "center"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#434b53"
blue = "#1bbcdd"
cyan = "#87acb4"
green = "#628d98"
magenta = "#bbe3ee"
red = "#d48678"
white = "#fee4ce"
yellow = "#fdd39f"

[colors.cursor]
cursor = "#fca02f"
text = "#08131a"

[colors.normal]
black = "#17384c"
blue = "#1e4950"
cyan = "#50a3b5"
green = "#027c9b"
magenta = "#68d4f1"
red = "#d15123"
white = "#deb88d"
yellow = "#fca02f"

[colors.primary]
background = "#09141b"
foreground = "#deb88d"

[colors.selection]
background = "#1e4962"
text = "#fee4ce"
