[rich]
panel_style = "on #001e27"
table_header_style = "bold #7a8f8e on #003748"
table_title_style = "bold #9cc2c3"
table_border_style = "#178ec8"
panel_border_style = "#178ec8"
column_output = "bold #9cc2c3"
column_value = "#9cc2c3"
bright_black = "#006488"
bright_blue = "#178ec8"
bright_cyan = "#00b39e"
bright_green = "#51ef84"
bright_magenta = "#e24d8e"
bright_red = "#f5163b"
bright_white = "#fcf4dc"
bright_yellow = "#b27e28"
normal_black = "#002831"
normal_blue = "#2176c7"
normal_cyan = "#259286"
normal_green = "#6cbe6c"
normal_magenta = "#c61c6f"
normal_red = "#d11c24"
normal_white = "#eae3cb"
normal_yellow = "#a57706"
cursor_cursor = "#f34b00"
cursor_text = "#002831"
table_show_lines = false
table_box = "SQUARE"
panel_padding = [ 0, 2,]
panel_title_align = "right"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#006488"
blue = "#178ec8"
cyan = "#00b39e"
green = "#51ef84"
magenta = "#e24d8e"
red = "#f5163b"
white = "#fcf4dc"
yellow = "#b27e28"

[colors.cursor]
cursor = "#f34b00"
text = "#002831"

[colors.normal]
black = "#002831"
blue = "#2176c7"
cyan = "#259286"
green = "#6cbe6c"
magenta = "#c61c6f"
red = "#d11c24"
white = "#eae3cb"
yellow = "#a57706"

[colors.primary]
background = "#001e27"
foreground = "#9cc2c3"

[colors.selection]
background = "#003748"
text = "#7a8f8e"
