[rich]
panel_style = "on #ffffff"
table_header_style = "bold #4d4d4c on #d6d6d6"
table_title_style = "bold #4d4d4c"
table_border_style = "#15a9fd"
panel_border_style = "#15a9fd"
column_output = "bold #4d4d4c"
column_value = "#4d4d4c"
bright_black = "#000000"
bright_blue = "#15a9fd"
bright_cyan = "#3e999f"
bright_green = "#1fc231"
bright_magenta = "#8959a8"
bright_red = "#ff0021"
bright_white = "#ffffff"
bright_yellow = "#d5b807"
normal_black = "#000000"
normal_blue = "#1dd3ee"
normal_cyan = "#3e999f"
normal_green = "#1f8c3b"
normal_magenta = "#8959a8"
normal_red = "#ff4d83"
normal_white = "#ffffff"
normal_yellow = "#1fc95b"
cursor_cursor = "#4d4d4c"
cursor_text = "#ffffff"
table_show_lines = true
table_box = "DOUBLE_EDGE"
panel_padding = [ 0, 2,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#000000"
blue = "#15a9fd"
cyan = "#3e999f"
green = "#1fc231"
magenta = "#8959a8"
red = "#ff0021"
white = "#ffffff"
yellow = "#d5b807"

[colors.cursor]
cursor = "#4d4d4c"
text = "#ffffff"

[colors.normal]
black = "#000000"
blue = "#1dd3ee"
cyan = "#3e999f"
green = "#1f8c3b"
magenta = "#8959a8"
red = "#ff4d83"
white = "#ffffff"
yellow = "#1fc95b"

[colors.primary]
background = "#ffffff"
foreground = "#4d4d4c"

[colors.selection]
background = "#d6d6d6"
text = "#4d4d4c"
