[rich]
panel_style = "on #2a2139"
table_header_style = "bold #f0eff1 on #181521"
table_title_style = "bold #f0eff1"
table_border_style = "#36f9f6"
panel_border_style = "#36f9f6"
column_output = "bold #f0eff1"
column_value = "#f0eff1"
bright_black = "#fefefe"
bright_blue = "#36f9f6"
bright_cyan = "#f92aad"
bright_green = "#72f1b8"
bright_magenta = "#e1acff"
bright_red = "#f88414"
bright_white = "#fefefe"
bright_yellow = "#fff951"
normal_black = "#fefefe"
normal_blue = "#6d77b3"
normal_cyan = "#f772e0"
normal_green = "#72f1b8"
normal_magenta = "#c792ea"
normal_red = "#f97e72"
normal_white = "#fefefe"
normal_yellow = "#fede5d"
cursor_cursor = "#72f1b8"
cursor_text = "#1a1a1a"
table_show_lines = true
table_box = "DOUBLE_EDGE"
panel_padding = [ 0, 2,]
panel_title_align = "left"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#fefefe"
blue = "#36f9f6"
cyan = "#f92aad"
green = "#72f1b8"
magenta = "#e1acff"
red = "#f88414"
white = "#fefefe"
yellow = "#fff951"

[colors.cursor]
cursor = "#72f1b8"
text = "#1a1a1a"

[colors.normal]
black = "#fefefe"
blue = "#6d77b3"
cyan = "#f772e0"
green = "#72f1b8"
magenta = "#c792ea"
red = "#f97e72"
white = "#fefefe"
yellow = "#fede5d"

[colors.primary]
background = "#2a2139"
foreground = "#f0eff1"

[colors.selection]
background = "#181521"
text = "#f0eff1"
