[rich]
panel_style = "on #262626"
table_header_style = "bold #ffffff on #4d4d4d"
table_title_style = "bold #d0d0d0"
table_border_style = "#86aed6"
panel_border_style = "#86aed6"
column_output = "bold #d0d0d0"
column_value = "#d0d0d0"
bright_black = "#1c1c1c"
bright_blue = "#86aed6"
bright_cyan = "#b1e7dd"
bright_green = "#aed686"
bright_magenta = "#d6aed6"
bright_red = "#d68686"
bright_white = "#efefef"
bright_yellow = "#e4c9af"
normal_black = "#1c1c1c"
normal_blue = "#86aed6"
normal_cyan = "#8adbb4"
normal_green = "#aed686"
normal_magenta = "#d6aed6"
normal_red = "#d68686"
normal_white = "#d0d0d0"
normal_yellow = "#d7af87"
cursor_cursor = "#e4c9af"
cursor_text = "#000000"
table_show_lines = true
table_box = "ROUNDED"
panel_padding = [ 2, 2,]
panel_title_align = "right"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#1c1c1c"
blue = "#86aed6"
cyan = "#b1e7dd"
green = "#aed686"
magenta = "#d6aed6"
red = "#d68686"
white = "#efefef"
yellow = "#e4c9af"

[colors.cursor]
cursor = "#e4c9af"
text = "#000000"

[colors.normal]
black = "#1c1c1c"
blue = "#86aed6"
cyan = "#8adbb4"
green = "#aed686"
magenta = "#d6aed6"
red = "#d68686"
white = "#d0d0d0"
yellow = "#d7af87"

[colors.primary]
background = "#262626"
foreground = "#d0d0d0"

[colors.selection]
background = "#4d4d4d"
text = "#ffffff"
