[rich]
panel_style = "on #1b1d1e"
table_header_style = "bold #ffffff on #4d4d4d"
table_title_style = "bold #f8f8f8"
table_border_style = "#3f78ff"
panel_border_style = "#3f78ff"
column_output = "bold #f8f8f8"
column_value = "#f8f8f8"
bright_black = "#505354"
bright_blue = "#3f78ff"
bright_cyan = "#23cfd5"
bright_green = "#b6e354"
bright_magenta = "#9e6ffe"
bright_red = "#ff5995"
bright_white = "#f8f8f2"
bright_yellow = "#feed6c"
normal_black = "#1b1d1e"
normal_blue = "#2757d6"
normal_cyan = "#38c8b5"
normal_green = "#4df840"
normal_magenta = "#8c54fe"
normal_red = "#f92672"
normal_white = "#ccccc6"
normal_yellow = "#f4fd22"
cursor_cursor = "#fc971f"
cursor_text = "#000000"
table_show_lines = false
table_box = "DOUBLE_EDGE"
panel_padding = [ 2, 2,]
panel_title_align = "left"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#505354"
blue = "#3f78ff"
cyan = "#23cfd5"
green = "#b6e354"
magenta = "#9e6ffe"
red = "#ff5995"
white = "#f8f8f2"
yellow = "#feed6c"

[colors.cursor]
cursor = "#fc971f"
text = "#000000"

[colors.normal]
black = "#1b1d1e"
blue = "#2757d6"
cyan = "#38c8b5"
green = "#4df840"
magenta = "#8c54fe"
red = "#f92672"
white = "#ccccc6"
yellow = "#f4fd22"

[colors.primary]
background = "#1b1d1e"
foreground = "#f8f8f8"

[colors.selection]
background = "#4d4d4d"
text = "#ffffff"
