[rich]
panel_style = "on #000000"
table_header_style = "bold #000000 on #b5d5ff"
table_title_style = "bold #ffffff"
table_border_style = "#0000ff"
panel_border_style = "#0000ff"
column_output = "bold #ffffff"
column_value = "#ffffff"
bright_black = "#555555"
bright_blue = "#0000ff"
bright_cyan = "#00ffff"
bright_green = "#00ff00"
bright_magenta = "#ff00ff"
bright_red = "#ff0000"
bright_white = "#e5e5e5"
bright_yellow = "#ffff00"
normal_black = "#878787"
normal_blue = "#44b4cc"
normal_cyan = "#44b4cc"
normal_green = "#ccff04"
normal_magenta = "#9933cc"
normal_red = "#ff6600"
normal_white = "#f5f5f5"
normal_yellow = "#ffcc00"
cursor_cursor = "#ffffff"
cursor_text = "#000000"
table_show_lines = false
table_box = "ROUNDED"
panel_padding = [ 0, 2,]
panel_title_align = "center"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#555555"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#e5e5e5"
yellow = "#ffff00"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#878787"
blue = "#44b4cc"
cyan = "#44b4cc"
green = "#ccff04"
magenta = "#9933cc"
red = "#ff6600"
white = "#f5f5f5"
yellow = "#ffcc00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#b5d5ff"
text = "#000000"
