[rich]
panel_style = "on #282b33"
table_header_style = "bold #c6c6c6 on #1f2024"
table_title_style = "bold #c6c6c6"
table_border_style = "#b2cff0"
panel_border_style = "#b2cff0"
column_output = "bold #c6c6c6"
column_value = "#c6c6c6"
bright_black = "#434750"
bright_blue = "#b2cff0"
bright_cyan = "#69abc5"
bright_green = "#8fd7d6"
bright_magenta = "#efccfd"
bright_red = "#fa7193"
bright_white = "#d3d3d3"
bright_yellow = "#d1dfff"
normal_black = "#34373e"
normal_blue = "#a6c1e0"
normal_cyan = "#5b94ab"
normal_green = "#7ebebd"
normal_magenta = "#e1c1ee"
normal_red = "#e06383"
normal_white = "#ababab"
normal_yellow = "#cccccc"
cursor_cursor = "#7ebebd"
cursor_text = "#1f2024"
table_show_lines = false
table_box = "HEAVY"
panel_padding = [ 2, 2,]
panel_title_align = "center"
table_row_styles = [ "", "underline",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#434750"
blue = "#b2cff0"
cyan = "#69abc5"
green = "#8fd7d6"
magenta = "#efccfd"
red = "#fa7193"
white = "#d3d3d3"
yellow = "#d1dfff"

[colors.cursor]
cursor = "#7ebebd"
text = "#1f2024"

[colors.normal]
black = "#34373e"
blue = "#a6c1e0"
cyan = "#5b94ab"
green = "#7ebebd"
magenta = "#e1c1ee"
red = "#e06383"
white = "#ababab"
yellow = "#cccccc"

[colors.primary]
background = "#282b33"
foreground = "#c6c6c6"

[colors.selection]
background = "#1f2024"
text = "#c6c6c6"
