[rich]
panel_style = "on #292a30"
table_header_style = "bold #dfdfe0 on #414453"
table_title_style = "bold #dfdfe0"
table_border_style = "#6bdfff"
panel_border_style = "#6bdfff"
column_output = "bold #dfdfe0"
column_value = "#dfdfe0"
bright_black = "#7f8c98"
bright_blue = "#6bdfff"
bright_cyan = "#dabaff"
bright_green = "#acf2e4"
bright_magenta = "#ff7ab2"
bright_red = "#ff8170"
bright_white = "#dfdfe0"
bright_yellow = "#ffa14f"
normal_black = "#414453"
normal_blue = "#4eb0cc"
normal_cyan = "#b281eb"
normal_green = "#78c2b3"
normal_magenta = "#ff7ab2"
normal_red = "#ff8170"
normal_white = "#dfdfe0"
normal_yellow = "#d9c97c"
cursor_cursor = "#dfdfe0"
cursor_text = "#292a30"
table_show_lines = true
table_box = "SQUARE"
panel_padding = [ 1, 2,]
panel_title_align = "center"
table_row_styles = [ "", "dim",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#7f8c98"
blue = "#6bdfff"
cyan = "#dabaff"
green = "#acf2e4"
magenta = "#ff7ab2"
red = "#ff8170"
white = "#dfdfe0"
yellow = "#ffa14f"

[colors.cursor]
cursor = "#dfdfe0"
text = "#292a30"

[colors.normal]
black = "#414453"
blue = "#4eb0cc"
cyan = "#b281eb"
green = "#78c2b3"
magenta = "#ff7ab2"
red = "#ff8170"
white = "#dfdfe0"
yellow = "#d9c97c"

[colors.primary]
background = "#292a30"
foreground = "#dfdfe0"

[colors.selection]
background = "#414453"
text = "#dfdfe0"
