[rich]
panel_style = "on #f0edec"
table_header_style = "bold #2c363c on #cbd9e3"
table_title_style = "bold #2c363c"
table_border_style = "#1d5573"
panel_border_style = "#1d5573"
column_output = "bold #2c363c"
column_value = "#2c363c"
bright_black = "#cfc1ba"
bright_blue = "#1d5573"
bright_cyan = "#2b747c"
bright_green = "#3f5a22"
bright_magenta = "#7b3b70"
bright_red = "#94253e"
bright_white = "#4f5e68"
bright_yellow = "#803d1c"
normal_black = "#f0edec"
normal_blue = "#286486"
normal_cyan = "#3b8992"
normal_green = "#4f6c31"
normal_magenta = "#88507d"
normal_red = "#a8334c"
normal_white = "#2c363c"
normal_yellow = "#944927"
cursor_cursor = "#2c363c"
cursor_text = "#f0edec"
table_show_lines = true
table_box = "MINIMAL"
panel_padding = [ 1, 2,]
panel_title_align = "left"
table_row_styles = [ "", "italic",]
table_safe_box = true
table_padding = [ 0, 1,]
table_collapse_padding = false
table_pad_edge = true
table_expand = false
table_show_footer = false
table_show_edge = true
table_leading = 0
table_style = "none"
table_footer_style = "none"
table_caption_style = "none"
table_title_justify = "center"
table_caption_justify = "center"
table_highlight = false

[colors.bright]
black = "#cfc1ba"
blue = "#1d5573"
cyan = "#2b747c"
green = "#3f5a22"
magenta = "#7b3b70"
red = "#94253e"
white = "#4f5e68"
yellow = "#803d1c"

[colors.cursor]
cursor = "#2c363c"
text = "#f0edec"

[colors.normal]
black = "#f0edec"
blue = "#286486"
cyan = "#3b8992"
green = "#4f6c31"
magenta = "#88507d"
red = "#a8334c"
white = "#2c363c"
yellow = "#944927"

[colors.primary]
background = "#f0edec"
foreground = "#2c363c"

[colors.selection]
background = "#cbd9e3"
text = "#2c363c"
