site_name: Flock - An agent framework
theme:
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  name: material
  palette:
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - I - Introduction:
          - Building Your First Flock Agent: examples/01_introduction/01_simple_example.md
          - Type Hints, and Tool Integration: examples/01_introduction/02_typed_output.md
          - Code Execution: examples/01_introduction/03_tool_and_code_agent.md
          - Descriptions: examples/01_introduction/04_descriptions.md
          - Data Class Integration and Caching: examples/01_introduction/05_typed_output2.md
          - Simple hand-off between two agents: examples/01_introduction/06_simple_hand_off.md
  - Flock In-Depth/Reference:
      - Flock: api/flock.md
      - FlockAgents: api/flock_agents.md

plugins:
  - termage:
      write_files: false
      inline_styles: true
      name_template: termage_{count}.svg
      path: assets
      background: "#212121"
      foreground: "#ffffff"
      tabs:
        - Python
        - Output
      chrome: true
      width: 100
      height: 200
  - search
  - mkdocstrings:
      handlers:
        python:
          show_root_toc_entry: false
          separate_signature: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
