apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: flock-dev-secretstore
  namespace: development
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: /secrets/secrets.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"
