"""Module that holds Models used by the server."""

from flock.components.server.models.events import (
    AgentActivatedEvent,
    AgentCompletedEvent,
    AgentErrorEvent,
    BatchItemAddedEvent,
    CorrelationGroupUpdatedEvent,
    MessagePublishedEvent,
    StreamingOutputEvent,
    SubscriptionInfo,
    VisibilitySpec,
)
from flock.components.server.models.graph import (
    GraphAgentMetrics,
    GraphArtifact,
    GraphEdge,
    GraphFilters,
    GraphMarker,
    GraphNode,
    GraphPosition,
    GraphRequest,
    GraphRequestOptions,
    GraphRun,
    GraphSnapshot,
    GraphState,
    GraphStatistics,
    GraphTimeRange,
    GraphTimeRangePreset,
)
from flock.components.server.models.models import (
    Agent,
    AgentList,
    AgentRunInput,
    AgentRunRequest,
    AgentRunResponse,
    AgentSubscription,
    CorrelationStatusResponse,
    MCPAgentInvokationResponse,
    MCPArtifactListResponse,
    MCPArtifactPublishResponse,
    MCPArtifactResponse,
    MCPArtifactSchemaResponse,
    MCPArtifactSummaryResponse,
    MCPArtifactTypeNamesResponse,
    MCPWorkflowStatusResponse,
    ProducedArtifact,
)


__all__ = [
    # models.py
    "Agent",
    # events.py
    "AgentActivatedEvent",
    "AgentCompletedEvent",
    "AgentErrorEvent",
    "AgentList",
    "AgentRunInput",
    "AgentRunRequest",
    "AgentRunResponse",
    "AgentSubscription",
    "BatchItemAddedEvent",
    "CorrelationGroupUpdatedEvent",
    "CorrelationStatusResponse",
    # graph.py
    "GraphAgentMetrics",
    "GraphArtifact",
    "GraphEdge",
    "GraphFilters",
    "GraphMarker",
    "GraphNode",
    "GraphPosition",
    "GraphRequest",
    "GraphRequestOptions",
    "GraphRun",
    "GraphSnapshot",
    "GraphState",
    "GraphStatistics",
    "GraphTimeRange",
    "GraphTimeRangePreset",
    # MCP unified response models
    "MCPAgentInvokationResponse",
    "MCPArtifactListResponse",
    "MCPArtifactPublishResponse",
    "MCPArtifactResponse",
    "MCPArtifactSchemaResponse",
    "MCPArtifactSummaryResponse",
    "MCPArtifactTypeNamesResponse",
    "MCPWorkflowStatusResponse",
    "MessagePublishedEvent",
    "ProducedArtifact",
    "StreamingOutputEvent",
    "SubscriptionInfo",
    "VisibilitySpec",
]
